# Generated by Django 5.1.2 on 2025-05-11 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('cacamba_2m', 'Caçamba 2m³'), ('cacamba_3m', 'Caçamba 3m³'), ('cacamba_4m', 'Caçamba 4m³'), ('caminhao_5m', 'Caminhão 5m³'), ('caminhao_12m', 'Caminhão 12m³'), ('caminhao_25m', 'Caminhão 25m³'), ('roll_roll_25m', 'Roll Roll 25m³'), ('roll_roll_32m', 'Roll Roll 32m³')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regiao_CG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_regiao', models.CharField(choices=[('SEGREDO', 'SEGREDO'), ('PROSA', 'PROSA'), ('CENTRO', 'CENTRO'), ('IMBIRUSSU', 'IMBIRUSSU'), ('LAGOA', 'LAGOA'), ('ANHANDUIZINHO', 'ANHANDUIZINHO'), ('BANDEIRA', 'BANDEIRA')], max_length=13, unique=True, verbose_name='Região')),
            ],
            options={
                'verbose_name': 'Região',
                'verbose_name_plural': 'Regiões',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('nome_usuario', models.CharField(max_length=150, verbose_name='Nome de usuário')),
                ('telefone', models.CharField(max_length=10, verbose_name='Telefone')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('nr_porta', models.CharField(max_length=5, verbose_name='Número de porta')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Bairros_CG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_bairro', models.CharField(max_length=150, unique=True, verbose_name='Bairro')),
                ('nome_regiao_regioes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.regiao_cg', to_field='nome_regiao', verbose_name='Nome Região')),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
            },
        ),
        migrations.CreateModel(
            name='Transportador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('nome_fantasia', models.CharField(max_length=150, unique=True, verbose_name='Nome transportador')),
                ('telefone_fixo', models.CharField(blank=True, max_length=16, verbose_name='Telefone Fixo')),
                ('telefone_extra', models.CharField(blank=True, max_length=16, verbose_name='Telefone Extra')),
                ('telefone_celular', models.CharField(blank=True, max_length=16, verbose_name='Telefone celular')),
                ('email', models.CharField(max_length=150, verbose_name='E-mail')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('nr_porta', models.CharField(max_length=5, verbose_name='Número de porta')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('regiao', models.CharField(choices=[('SEGREDO', 'SEGREDO'), ('PROSA', 'PROSA'), ('CENTRO', 'CENTRO'), ('IMBIRUSSU', 'IMBIRUSSU'), ('LAGOA', 'LAGOA'), ('ANHANDUIZINHO', 'ANHANDUIZINHO'), ('BANDEIRA', 'BANDEIRA')], max_length=13, verbose_name='Região')),
                ('is_ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('regioes_trabalho', models.ManyToManyField(to='core.regiao_cg', verbose_name='Regiões de Trabalho')),
            ],
            options={
                'verbose_name': 'Transportador',
                'verbose_name_plural': 'Transportadores',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('numero_pedido', models.IntegerField(editable=False, unique=True, verbose_name='Número do Pedido')),
                ('status_pedido', models.CharField(choices=[('NOVO', 'NOVO'), ('PENDENTE', 'PENDENTE'), ('ATENDIDO', 'ATENDIDO'), ('FINALIZADO', 'FINALIZADO'), ('CANCELADO', 'CANCELADO'), ('ARQUIVADO', 'ARQUIVADO')], default='NOVO', max_length=10, verbose_name='Status')),
                ('tipo_entulho', models.CharField(max_length=20, verbose_name='Tipo de Entulho')),
                ('quantidade_desejada', models.IntegerField(verbose_name='Quantidade Desejada')),
                ('logradouro', models.CharField(max_length=255)),
                ('num_porta', models.CharField(max_length=10)),
                ('bairro', models.CharField(default='Não informado', max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_retirada', models.DateField(verbose_name='Data de Retirada')),
                ('nome_cliente', models.CharField(max_length=255)),
                ('telefone_cliente', models.CharField(max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('recebido', models.BooleanField(default=False, verbose_name='Recebido')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Obs:')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto', verbose_name='Produto')),
                ('transportador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transportador', verbose_name='Transportador')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='TransportadorProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('qtd_produto', models.IntegerField(null=True, verbose_name='Quantidade do produto')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
                ('transportador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transportador')),
            ],
        ),
        migrations.AddField(
            model_name='transportador',
            name='produtos',
            field=models.ManyToManyField(through='core.TransportadorProduto', to='core.produto'),
        ),
    ]
