# Generated by Django 5.1.2 on 2025-04-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='recebido',
            field=models.BooleanField(default=False, verbose_name='Recebido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_entulho',
            field=models.CharField(max_length=20, verbose_name='Tipo de Entulho'),
        ),
    ]
