# Generated by Django 5.1.2 on 2024-10-16 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('cacamba_2m', 'Caçamba 2m³'), ('cacamba_3m', 'Caçamba 3m³'), ('cacamba_4m', 'Caçamba 4m³'), ('caminhao_5m', 'Caminhão 5m³'), ('caminhao_12m', 'Caminhão 12m³'), ('caminhao_25m', 'Caminhão 25m³'), ('roll_roll_25', 'Roll Roll 25m³'), ('roll_roll_32', 'Roll Roll 32m³')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransportadorProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
                ('transportador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transportador')),
            ],
        ),
        migrations.AddField(
            model_name='transportador',
            name='produtos',
            field=models.ManyToManyField(through='core.TransportadorProduto', to='core.produto'),
        ),
    ]
