# Generated by Django 5.1.2 on 2025-07-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportador',
            name='senha',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='transportador',
            name='email',
            field=models.CharField(max_length=150, unique=True, verbose_name='E-mail'),
        ),
    ]
