# Generated by Django 5.1.2 on 2025-05-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pedido_recebido_alter_pedido_tipo_entulho'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Obs:'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status_pedido',
            field=models.CharField(choices=[('NOVO', 'NOVO'), ('PENDENTE', 'PENDENTE'), ('ATENDIDO', 'ATENDIDO'), ('FINALIZADO', 'FINALIZADO'), ('CANCELADO', 'CANCELADO'), ('ARQUIVADO', 'ARQUIVADO')], default='NOVO', max_length=10, verbose_name='Status'),
        ),
    ]
