# Generated by Django 5.1.2 on 2024-10-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto_transportadorproduto_transportador_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportadorproduto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
