# Generated by Django 5.1.2 on 2025-07-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transportador_senha_alter_transportador_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportador',
            name='email',
            field=models.CharField(max_length=150, verbose_name='E-mail'),
        ),
    ]
