# Generated by Django 5.1.2 on 2025-07-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_transportador_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportador',
            name='cnpj',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='CNPJ'),
        ),
    ]
