# Generated by Django 5.1.2 on 2024-10-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_transportadorproduto_preco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportador',
            name='qtd_cacambas',
        ),
        migrations.AddField(
            model_name='transportadorproduto',
            name='qtd_produto',
            field=models.IntegerField(null=True, verbose_name='Quantidade do produto'),
        ),
    ]
