# Generated by Django 5.1.2 on 2025-07-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transportador_cnpj'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportador',
            options={'ordering': ['is_ativo', 'nome_fantasia'], 'verbose_name': 'Transportador', 'verbose_name_plural': 'Transportadores'},
        ),
        migrations.AlterField(
            model_name='transportador',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='transportador',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='E-mail'),
        ),
    ]
