# Generated by Django 5.1.2 on 2025-08-19 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_transportador_options_alter_transportador_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status_pedido',
            field=models.CharField(choices=[('NOVO', 'NOVO'), ('PENDENTE', 'PENDENTE'), ('ATENDIDO', 'ATENDIDO'), ('FINALIZADO', 'FINALIZADO'), ('CANCELADO', 'CANCELADO')], default='NOVO', max_length=10, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('ESTORNADO', 'Estornado')], default='PENDENTE', max_length=10)),
                ('metodo', models.CharField(choices=[('CARTAO', 'Cartão'), ('PIX', 'PIX'), ('BOLETO', 'Boleto'), ('DINHEIRO', 'Dinheiro')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/')),
                ('observacoes', models.TextField(blank=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='core.pedido')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
    ]
