# Generated by Django 5.1.2 on 2024-11-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_transportador_qtd_cacambas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='longitude',
        ),
    ]
