# Generated by Django 5.1.2 on 2025-08-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pagamento_confirmado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('AGUARDANDO', 'AGUARDANDO')], default='PENDENTE', max_length=10),
        ),
    ]
