# Generated by Django 5.1.2 on 2025-08-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_pagamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='comissao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
